### ISSUE TITLE
What speak agains using a passed monaco instance like in `emmetHTML` from 'emmet-monaco-es'

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#12]
basically im asking to revert:
https://github.com/remcohaszing/monaco-tailwindcss/commit/c0a98fa36c5826e0011cc5efd2d32fe8688f5304

i had this build problem once that i included monaco two times - i had it fixed but now its there again (probably because im using it via `file:../../` and the node_modules are bugged or something) -> but why not handle it like  `emmetHTML` from 'emmet-monaco-es'
https://github.com/troy351/emmet-monaco-es#esm

the do it like:

`emmetHTML(monaco, ['html', 'php'])`

they pass a complete monaco instance which will be used to handle everyting, it even has the advantage that one can use monaco from a cdn and pass `window.monaco`

what do you think?

developing via `file:../../../../../monaco-tailwindcss` is sometimes a pain as monaco is often bundled twice

**Comment by mhsdesign** [comment]
btw by monaco i mean: `import * as monaco from 'monaco-editor'` or `import type * as Monaco from 'monaco-editor'`

**Comment by remcohaszing** [comment]
Yes, I understand. :)

I think it’s a good idea. I’ve updated `monaco-worker-manager` to support this.

**Comment by mhsdesign** [comment]
my current workaround was to use `rm -rf ./node_modules/monaco-tailwindcss/node_modules/monaco-editor` sometime (when linking from local via file: in yarn)

or using:
```js
onResolve({ filter: /^monaco-editor$/ }, () => ({
    path: fileURLToPath(new URL('./node_modules/monaco-editor/esm/vs/editor/editor.main.js', import.meta.url))
}));
onResolve({ filter: /^monaco-editor\/.*$/ }, ({ path }) => ({
    path: fileURLToPath(new URL('./node_modules/' + path, import.meta.url))
}));
```

**Comment by mhsdesign** [comment]
nice thanks for updating that (reference https://github.com/remcohaszing/monaco-worker-manager/commit/8901950e03735fcea8d83a55e16b30e3dc1d8e75)
