### ISSUE TITLE
Publish an early beta

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#13]

**Comment by remcohaszing** [comment]
A build script was the minimal requirement for that. So thanks for implementing that!

I’ll spend a lot of time on this tomorrow and make sure to create a release near the end of the day. I’ll create `0.x` releases until this is stable as per semver.

I’m still in doubt about the name. Should we keep `monaco-tailwindcss` or rename it to `monaco-tailwind`? I don’t want to change it after releasing.

**Comment by mhsdesign** [comment]
hmmm tailwindcss is like fully qualified ... it has to fit in your `/monaco-[a-z]+/` suite i guess ^^ which both does
monaco-yaml is real short though ...

**Comment by remcohaszing** [comment]
I released it as `monaco-tailwindcss` :rocket:

**Comment by mhsdesign** [comment]
cool :D thanks 😄
