### ISSUE TITLE
Support older tailwindcss versions

### ISSUE THREAD

**Issue by remcohaszing** [remcohaszing/monaco-tailwindcss#27]
The playground on https://play.tailwindcss.com supports tailwindcss versions 1, 2, and 3. Should we support this too?

**Comment by mhsdesign** [comment]
i found it good that we do not, as this increases the complexity a lot, with questioning advantages.

i would like to have answered why you/we even build this package - sure because first of: we are awesome ^^

**Comment by remcohaszing** [comment]
I have no personal interest in this either, but I do wish the @tailwindlabs team gets attention of this project and uses it for their playground, so we can cooperate with them. Since their playground supports it, I think we may need to as well.

---

> i would like to have answered why you/we even build this package

I’m working on this so it can be used in [Motif](http://motif.land). :smile:

**Comment by remcohaszing** [comment]
If we do decide not to support older versions of Tailwindcss, we can do some cleanups. I.e. we don’t have to use the modules from the jit state in `getVariants`, we could use regular imports instead.

**Comment by mhsdesign** [comment]
Or maybe the tailwind guys don't need the version switcher... after all who uses tailwind 2 when you've got 3? This seems a bit overkill.

**Comment by remcohaszing** [comment]
I’m convinced we probably won’t need to support this. I’ll close the issue. If there turns out to be user demand, we can reconsider this.
