### ISSUE TITLE
Support for `typography` plugin or general plugins

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#32]
I dindt test this yet but the current implementation might not allow plugins.

It would be great to have support 

A: For any plugins in general
or
B: Built in support for only selected super important plugins, say ([typography](https://github.com/tailwindlabs/tailwindcss-typography)/ [line-clamp](https://github.com/tailwindlabs/tailwindcss-line-clamp))

I previously opposed to this since but the tailwind `typography` plugin is a real game changer and involved many times that it would be great to allow this somehow.

**Comment by mhsdesign** [comment]
the problem is - we cannot postMessage an object with functions to a webworker as this is not supported by the cloning: https://stackoverflow.com/questions/7704323/passing-objects-to-a-web-worker#answer-45001480

so i have no clue how to solve this cleanly when we want to allow every kind of plugin ... they do it by not using webworkers: https://github.com/beyondcode/tailwindcss-jit-cdn

and playtailwind uses eval on a fake common js javascript string.

i can imagine allowing a static string as plugin which must be one of these below:
```json
{
  "plugins": [
    "@tailwindcss/typography",
    "@tailwindcss/forms",
    "@tailwindcss/line-clamp",
    "@tailwindcss/aspect-ratio",
  ]
}
```
we would import these plugins in the webworker and replace those strings with the actual plugin inside the webworker so `resolveConfig` gets a nice config.


custom plugins can only work via passing a string and using eval.
```
{
  "plugins": [
    {
      "myPlugin": "plugin(function ({ addComponents }) {
        addComponents({
        '.btn': {
          padding: '.5rem 1rem',
          borderRadius: '.25rem',
          fontWeight: '600',
        },
      });
    }),"
  }
  ]
}
```

**Comment by mhsdesign** [comment]
after implementing this, i dont like that we merge our custom options into the tailwindConfig, they might be better of namespaced in the `tailwindConfig` or as a separate method argument for setUpMonaco...

**Comment by remcohaszing** [comment]
This has been fixed now by allowing custom processing in the worker.
