### ISSUE TITLE
TS Types

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#33]
i somehow only found that yet. maybe there are things we could need.

https://github.com/tailwindlabs/play.tailwindcss.com/blob/5ae52d6c44ed522260f3a22c56aef2df098f0bb8/src/monaco/types-v3.d.ts

or just `@types/tailwindcss`

**Comment by remcohaszing** [comment]
They use that for type hints on hover. It might be useful to move `@types/tailwindcss` from `devDependencies` to `dependencies` though. It’s used in our public interface.

**Comment by remcohaszing** [comment]
Those type definitions are used to provide TypeScript integration in the playground. They could just have used `@types/tailwindcss` instead.
