### ISSUE TITLE
Expose certain tailwind css parts to avoid install of (another) tailwind? 

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#40]
when using this plugin (with bundled tailwind) and additionally installing tailwindcss to use parts like the plugin api -
this could be simplified (in terms of node_modules size) https://github.com/remcohaszing/monaco-tailwindcss/pull/34#issuecomment-1097742235

But probably not worth it and rather cumbersome.

**Comment by remcohaszing** [comment]
The idea is interesting. It seems the tailwind plugin API doesn’t import anything else, so its not that bad. However, I don’t think they’ll consider it a breaking change to suddenly add imports there.

**Comment by mhsdesign** [comment]
> However, I don’t think they’ll consider it a breaking change to suddenly add imports there.

this is concerning about the possibility of duplicate code right?

**Comment by mhsdesign** [comment]
i will close this, as this is a rare usecase...
