### ISSUE TITLE
FEATURE: Expose api to `generateStylesFromContent`

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#6]
if one wants to collect all the css rules for the jit tailwind classes (for some kind of live editor), currently i think one needs to use a second package like what i have done here:
https://github.com/mhsdesign/jit-browser-tailwindcss

but it would be much more comfortable to expose an internal tailwind jit api - (as we need to mock so much of node builtins already and have tailwind and postcss imported)

i could also imagine to somehow collect all the generated rules, that are shown on hover

**Comment by mhsdesign** [comment]
or find another way to reproduce the smooth editing and live preview behaviour of https://play.tailwindcss.com/
(one doesnt even need to press enter there, alone arrow key selecting the class of the list is enough to apply it...)

i could imagine passing some callback handler into `configureMonacoTailwindcss` since we cant know where to add these live styles ...

**Comment by mhsdesign** [comment]
and ideally tailwind play could be using this package ... (but maybe not as they have some crazy spagetty code tailwind version 1,2,3 switcher in there ...)

**Comment by remcohaszing** [comment]
I think it’s a very useful feature! Also it’s doable.

Basically what needs to happen is:

- In `tailwindcssWorker.ts` implement a method to generate the styles.
- Expose this method via the main thread in `index.ts`. I imagine `configureMonacoTailwindcss` can expose a method to call the worker method. It would return something like this interface:

  ```ts
  export interface MonacoTailwindcssProvider extends IDisposable {
    generateStylesFromContent: () => Promise<string>;
  }
  ```
