### ISSUE TITLE
Build: our "make every dependency `sideEffects: false` hack" doesnt work.

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#67]
Thats our hack: With the expectation for better treeshaking.

https://github.com/remcohaszing/monaco-tailwindcss/blob/main/build.js#L83-L85
```js
        // None of our dependencies use side effects, but many packages don’t explicitly define
        // this.
        onResolve({ filter: /.*/ }, () => ({ sideEffects: false }));
```

The problem is, it doesnt work. (Sorry :P)

The second problem is, we wont see a difference for this project / eg we cant test it event _if_ it worked.

See, in this 'monaco-tailwindcss' build, there is nothing more to treeshake with or without sideEffects so the bundle size is the same even if all our dependencies have no side effects.

--------

I recently worked on another project and remembered your hack and applied it because i found unused import statements in the bundle. But this hack dindt worked there - the bundle size stayed the same, and also the unused import where still left.

I searched a bit and found this issue: https://github.com/evanw/esbuild/issues/1895
Apparently someone tried the same thing.

> Okay, I see now. Not passing back a definite path will invoke the esbuild default resolver, which will just override the sideEffects property to true.

this is how it should be [done](https://github.com/evanw/esbuild/issues/1895#issuecomment-1003404929):

```js
onResolve({ filter: /.*/, namespace: "file" }, async ({ path, ...options }) => {
  const result = await resolve(path, { ...options, namespace: "noRecurse"})
  return { ...result, sideEffects: false }
})
```

but in our case, it doesnt matter (for now...)

**Comment by remcohaszing** [comment]
Really? Feel free to remove it then.
