### ISSUE TITLE
CommonJS or AMD dependencies issue

### ISSUE THREAD

**Issue by faizananwerali** [remcohaszing/monaco-tailwindcss#68]
`
Warning: /Users/admin/Documents/AngularProjects/DoBusiness/node_modules/monaco-tailwindcss/tailwindcss.worker.js depends on 'line-column'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/admin/Documents/AngularProjects/DoBusiness/node_modules/monaco-tailwindcss/tailwindcss.worker.js depends on 'postcss-nested'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/admin/Documents/AngularProjects/DoBusiness/node_modules/monaco-tailwindcss/tailwindcss.worker.js depends on 'postcss-selector-parser'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/admin/Documents/AngularProjects/DoBusiness/node_modules/monaco-tailwindcss/tailwindcss.worker.js depends on 'postcss-value-parser'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/admin/Documents/AngularProjects/DoBusiness/node_modules/monaco-tailwindcss/tailwindcss.worker.js depends on 'semver'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

`

**Comment by remcohaszing** [comment]
These warnings show that some dependencies are the issue, not `monaco-tailwindcss` itself. I too wish the community moves on to ESM, but that isn’t reality at this moment. I suggest you disable these warnings and/or report issues to the dependencies mentioned.
