### ISSUE TITLE
Possible performance regression from v0.4.2 to v0.5.0?

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#73]
Hi again :D
I have some e2e tests with playwright testing the behaviour of the monaco editor with tailwind and my whole integration.
They still seem to work perfectly with v0.4.2 but when upgrading to v0.5.0 some seem to fail constantly due to timing issues.
After sleeping for 500ms at a few points it seems to be working again but is obviously not ideal.
Do you have a guess what could have affected this? Maybe tailwind 3.2 is more performance hungry or something... 
Its just odd that it seems to be notable ...

**Comment by mhsdesign** [comment]
After adjusting the timing it seems to work now reliable so no need to investigate i think

**Comment by remcohaszing** [comment]
Sorry, I saw the notification for this, but forgot about it.

I have integrated this library in a project, but I don’t use it a lot myself. It’s good to report such regressions if you suspect them.

After your last comment, my guess is it might have been a caching issue? The old version was cached, but not the new one. I’m just guestimating though.

**Comment by mhsdesign** [comment]
no problem :) i suspect tailwind 3.2 is just a bit more performance hungry or sth.
it was not a caching problem as it was tested via playwright isolated ^^
but when using it manually i couldnt find anything so everything fine.
