### ISSUE TITLE
[Q&A] Can this package be used within a Next.js project?

### ISSUE THREAD

**Issue by lautarodapin** [remcohaszing/monaco-tailwindcss#74]
Can someone give me an example? I could not figure it out how to make it work.

**Comment by remcohaszing** [comment]
Yes. In fact, I'm using it with Next.js 🙂

Have you gotten Monaco editor to work without warnings? If so, how? Import `monaco-editor`? CDN? Webpack plugin?

**Comment by remcohaszing** [comment]
I'm closing this issue, because it's a question, not an issue with this project.

**Comment by dinhanhthi** [comment]
@remcohaszing : Can you give us an example of integrating this within nextjs, please?

**Comment by remcohaszing** [comment]
When I wrote this, it was for a client integrating this in a Next.js application, so it is possible. It has been a while though, so I can’t really help. I suggest you start by making sure you use `monaco-editor` in your project, not Monaco from a CDN. This involves configuring Webpack in your Next.js project, and making sure Monaco is only used in client components. If you get this to work, integrating `monaco-tailwindcss` should be easy. Also please report your findings to https://github.com/vercel/next.js/pull/49762 if you get it to work.

**Comment by remcohaszing** [comment]
See https://github.com/remcohaszing/monaco-yaml/issues/219#issuecomment-2198118949
