### ISSUE TITLE
How can I use this in a monaco editor core 

### ISSUE THREAD

**Issue by kromate** [remcohaszing/monaco-tailwindcss#82]

**Comment by kromate** [comment]
@remcohaszing @mhsdesign

**Comment by mhsdesign** [comment]
i dont understand.

please have a look at the examples over at https://github.com/remcohaszing/monaco-tailwindcss/tree/main/examples

and try to experiment with them.

if you have any follow up questions please try to be a little more vague ;)

**Comment by kromate** [comment]
Hi, Sorry for the unclear issue. So I am trying to create an editor that can be used to create vue components. was able to get Volar (Vue language extension) to work on the edit but when I try to do so for tailwindcss extension it doesn't work

i get an error like this in the console
`Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:504:31)
    at null:129215:22`

below is how I try to use it

`import * as monaco from 'monaco-editor-core'
import { configureMonacoTailwindcss, tailwindcssData } from 'monaco-tailwindcss'
import TailwindcssWorker from 'monaco-tailwindcss/tailwindcss.worker.js?worker'

configureMonacoTailwindcss(monaco as any, {})

export function loadMonacoEnv(store: Store) {
  (self as any).MonacoEnvironment = {
    async getWorker(_: any, label: string) {
      switch (label) {
        case 'vue':
          return new vueWorker()
        case 'tailwindcss':
          return new TailwindcssWorker()
        default:
          return new editorWorker()
      }
    }
  }
`

**Comment by kromate** [comment]
I can create a stackblitz sample if needed

**Comment by remcohaszing** [comment]
Have you installed `monaco-editor`? Unfortunately `monaco-tailwindcss` still depends on `monaco-editor` for the web worker, though it doesn’t pull in all of Monaco editor in your bundle.

**Comment by remcohaszing** [comment]
I’m closing this, as it doesn’t appear to be an issue with `monaco-tailwindcss`.
