### ISSUE TITLE
No hints in React

### ISSUE THREAD

**Issue by rick-chou** [remcohaszing/monaco-tailwindcss#83]
Hey, I'm trying to build my own React REPL in which I've built in tailwind syntax, but it seems that after `monaco-editor` is configured with typescript language, the library doesn't support syntax hints, but you can still see the content on mouse hover, for example

https://monaco-tailwindcss.js.org/#mdx

**Comment by remcohaszing** [comment]
I’m not really sure I understand. Can you post a screenshot / screencast to show the problem? Or ideally a repo to reproduce it.

**Comment by rick-chou** [comment]
Sorry , I'm still a novice English speaker, thank you very much for your reply!

What I mean is that the code hints work when the language of monaco-editor is html / css, but not when the language is typescript.

language : html  -- works
<img width="1448" alt="Screenshot 2023-08-30 at 21 04 56" src="https://github.com/remcohaszing/monaco-tailwindcss/assets/56244178/c58240e2-786e-4fa2-a0e8-91e5a0e2a1ab">

language : typescript  --  not work
<img width="1483" alt="Screenshot 2023-08-30 at 21 05 10" src="https://github.com/remcohaszing/monaco-tailwindcss/assets/56244178/df653e85-d589-4fe6-a23e-0272618b4d32">

My question is, is it possible to set the language of monaco-editor to typescript and still have the syntax prompt?

**Comment by remcohaszing** [comment]
> Sorry , I'm still a novice English speaker, thank you very much for your reply!

No problem! So far it’s not that bad actually.

---

Ah, I think I understand the problem.

For HTML

1. https://monaco-tailwindcss.js.org/#html
2. Move the cursor towards the end of a class attribute
3. Press <kbd>Space</kbd> followed by <kbd>b</kbd>
4. A pop-up appears showing all autocompletions starting with `b`

For MDX

1. https://monaco-tailwindcss.js.org/#mdx
2. Move the cursor towards the end of a className prop
3. Press <kbd>Space</kbd> followed by <kbd>b</kbd>
4. Nothing happens
5. Press <kbd>Ctrl</kbd> + <kbd>Space</kbd>
6. A pop-up appears showing all autocompletions starting with `b`

For TypeScript you’re seeing the same behaviour as for MDX?

**Comment by rick-chou** [comment]
Yes, that's what I meant. But I'm using Macos.
Press <kbd>Ctrl</kbd> + <kbd>Space</kbd> triggers the switching of input method

**Comment by rick-chou** [comment]
BTW,  Why does mdx needs an extra button <kbd>Ctrl</kbd> to show the pop up?

**Comment by remcohaszing** [comment]
`CompletionItemProvider` accepts an optional array `triggerCharacters`. As far as I’m aware, this is supposed to determine after which character the completions show up automatically. I don’t understand why this behaviour is currently different between HTML and MDX.

I’m not going to look into this for now, but you can if you want. Feel free to ask if you have any questions.

**Comment by rick-chou** [comment]
Anyway thanks a lot!
