### ISSUE TITLE
Script failed to load

### ISSUE THREAD

**Issue by georgeamine** [remcohaszing/monaco-tailwindcss#86]
The script at 'https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/monaco-tailwindcss/tailwindcss.worker.js' failed to load.
Visiting the URL it does't exist anymore.

**Comment by remcohaszing** [comment]
I’m not sure where you found that URL, but `monaco-tailwindcss` isn’t shipped with `monaco-editor`. That URL never existed.
