### ISSUE TITLE
List features that work and that dont work

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#9]
|  Feature  | Info |
| ----- | --------|
| auto completion | ✅ ![image](https://user-images.githubusercontent.com/85400359/161913559-9c0a9058-20f8-4589-a85a-f234f4a1f6ec.png) |
| custom tailwind config | ✅ |
| linting | ✅ |
| arbitrary values  |  ✅  |
| edit arbitrary color values  | ✅ ![image](https://user-images.githubusercontent.com/85400359/161913024-56b53827-3f6e-4803-9f0e-69cd20dab0aa.png) |
| color preview  | ✅ ![image](https://user-images.githubusercontent.com/85400359/161914081-902feb6a-e423-46a2-8a91-e0273bd77177.png) |
| variant autocompletion | ✅ |
| hover support | ✅ ![image](https://user-images.githubusercontent.com/85400359/161913422-f7b5721c-cee0-4278-97df-1af12b3ec506.png) |

**Comment by mhsdesign** [comment]
Support for custom css classes from the tailwind base css doesnt work in the playground either https://play.tailwindcss.com/ so its to assume its not implemented anywhere. Also I would recommend using a tailwind plugin to introduce new classes.

**Comment by remcohaszing** [comment]
Everything here is checked. I’m closing this issue, because it’s not actionable.

If we ever find out about a missing new feature, let’s create a separate issue for that.
