### ISSUE TITLE
Format option add space

### ISSUE THREAD

**Issue by krstivoja** [remcohaszing/monaco-tailwindcss#91]
if you write 
`hover:bg-red-300`

and do right click format you will end up with

`hover: bg-red-300`

**Comment by remcohaszing** [comment]
This issue is unclear. What is the full model content? What’s the language?

Regardless, `monaco-tailwindcss` doesn’t provide a formatting provider. The issue must come from somewhere else.

**Comment by remcohaszing** [comment]
I see, so it’s just an issue in the demo. Fixed it. Thanks for reporting!

**Comment by krstivoja** [comment]
How did you fixed it as i have the same issue when i try to use it in my app. Thanks

**Comment by remcohaszing** [comment]
I updated `monaco-editor` from 0.44 to 0.52. I could reproduce the issue locally before, but not after the update.

**Comment by krstivoja** [comment]
Great! Thank you!
